# Generated by Django 5.1.5 on 2025-02-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
